import type {Metadata} from 'next'

export const metadata: Metadata = {
  title: 'Shelley Bressman Photography',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-[#e1dcd8] flex h-screen max-h-screen`}>
        <main className="grow h-screen lg:overflow-y-scroll flex-1">{children}</main>
      </body>
    </html>
  )
}
